services:

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: tareas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase_runner
    depends_on:
      db:
         condition: service_healthy
    volumes:
      - ./LIQUIBASE:/liquibase/CHANGELOG
      - ./LIQUIBASE/DRIVERS:/liquibase/lib
    working_dir: /liquibase/CHANGELOG
    command:
      - "--url=jdbc:postgresql://db:5432/tareas_db"
      - "--changeLogFile=changelog.yml"
      - "--username=postgres"
      - "--password=postgres"
      - "update"
    networks:
      - app-network

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tareas_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      liquibase:
        condition: service_completed_successfully
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger-ui.html"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./FRONT
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  app-network:
    driver: bridge